name: Vib PR

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: vanilla-os/vib-gh-action@v0.7.2
      with:
        recipe: 'recipe.yml'
        plugins: 'Vanilla-OS/vib-fsguard:v1.2-1'

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag testing .

    - uses: actions/upload-artifact@v4
      with:
        name: Containerfile
        path: Containerfile