name: Vib Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: vanilla-os/vib-gh-action@v0.3.3-1
      with:
        recipe: 'recipe.yml'
        plugins: 'Vanilla-OS/vib-fsguard:v1.2-1'

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag ghcr.io/simon511000/simon-vanilla-desktop:main .

    # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      if: github.repository == 'simon511000/simon-vanilla-desktop'
      run: |
        docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
        docker image push "ghcr.io/simon511000/simon-vanilla-desktop:main"
